# Generated by Django 6.1.1 on 2026-09-25 14:54

from django.conf import settings
from django.db import migrations, models


def detach_domains_of_deleted_websites(apps, schema_editor):
    Domain = apps.get_model("core", "Domain")
    Domain.objects.filter(website__deleted=True).update(website=None)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(detach_domains_of_deleted_websites, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='website',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='website',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted', False)), fields=('owner', 'name'), name='unique_active_website_name_per_owner', violation_error_message='You already have a website with this name.'),
        ),
    ]
