# Generated by Django 6.1.1 on 2026-09-25 16:00

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_website_name_per_owner"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="website",
            name="owner",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="%(class)ss", to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.CreateModel(
            name="Webserver",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                ("deleted", models.BooleanField(default=False)),
                ("ipv4", models.GenericIPAddressField(blank=True, null=True, protocol="IPv4")),
                ("ipv6", models.GenericIPAddressField(blank=True, null=True, protocol="IPv6")),
                ("cname", models.CharField(blank=True, max_length=255)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="%(class)ss",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="domain",
            name="webserver",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="domains",
                to="core.webserver",
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(
                condition=models.Q(("website__isnull", True), ("webserver__isnull", True), _connector="OR"),
                name="domain_single_host",
                violation_error_message="A domain can belong to either a website or a webserver, not both.",
            ),
        ),
        migrations.AddConstraint(
            model_name="webserver",
            constraint=models.UniqueConstraint(
                condition=models.Q(("deleted", False)),
                fields=("owner", "name"),
                name="unique_active_webserver_name_per_owner",
                violation_error_message="You already have a webserver with this name.",
            ),
        ),
        migrations.AddConstraint(
            model_name="webserver",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("ipv4__isnull", False),
                    ("ipv6__isnull", False),
                    models.Q(("cname", ""), _negated=True),
                    _connector="OR",
                ),
                name="webserver_has_address",
                violation_error_message="Set at least one of IPv4, IPv6 or CNAME.",
            ),
        ),
    ]
