# Generated by Django 6.1.1 on 2026-09-26 08:33

import core.models
from django.conf import settings
from django.db import migrations, models


def rotate_tokens(apps, schema_editor):
    # `AddField` evaluates the default once, give every existing domain its own token
    Domain = apps.get_model("core", "Domain")
    for domain in Domain.objects.only("pk"):
        domain.token = core.models.new_verification_token()
        domain.save(update_fields=["token"])


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_webserver"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="token",
            field=models.CharField(default=core.models.new_verification_token, editable=False, max_length=64),
        ),
        migrations.RunPython(rotate_tokens, migrations.RunPython.noop),
        migrations.AddField(
            model_name="domain",
            name="verified_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="domain",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                fields=("owner", "name"),
                name="unique_domain_name_per_owner",
                violation_error_message="You already have a domain with this name.",
            ),
        ),
    ]
