# Generated by Django 6.1.1 on 2026-09-26 11:46

from django.conf import settings
from django.db import migrations, models


def keep_latest_verification(apps, schema_editor):
    # a name may be verified by one owner only, keep the latest verification, the one nginx served so far
    Domain = apps.get_model("core", "Domain")
    kept = set()
    for domain in Domain.objects.filter(verified_at__isnull=False).order_by("-verified_at").only("pk", "name"):
        if domain.name in kept:
            domain.verified_at = None
            domain.save(update_fields=["verified_at"])
        kept.add(domain.name)


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_domain_verification"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="domain",
            name="managed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.RunPython(keep_latest_verification, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.UniqueConstraint(
                condition=models.Q(("verified_at__isnull", False)),
                fields=("name",),
                name="unique_verified_domain_name",
                violation_error_message="This domain is already in use.",
            ),
        ),
        migrations.AddConstraint(
            model_name="domain",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("managed", False),
                    models.Q(("verified_at__isnull", False), ("webserver__isnull", True), ("wildcard", False)),
                    _connector="OR",
                ),
                name="managed_domain_verified_website",
                violation_error_message="A managed domain is always verified, no wildcard and only for websites.",
            ),
        ),
    ]
