[project]
name = "ms-dome"  # TODO
description = "Backend for MSDome"  # TODO
version = "0.0.1"
license = "MIT"  # TODO
authors = [
    { name = "Paul-B98", email = "115164840+Paul-B98@users.noreply.github.com" }  # TODO
]
maintainers = [
    { name = "Paul-B98", email = "115164840+Paul-B98@users.noreply.github.com" }  # TODO
]
readme = "README.md"
keywords = ["Python Lib"]  # TODO
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
requires-python = ">=3.14"
dependencies = [
    "django>=6.1.1",
    "django-ninja>=1.7.0",
    "gunicorn>=26.2.0",
    "mozilla-django-oidc>=5.0.2",
    "psycopg[binary]>=3.3.5",
    "pyjwt[crypto]>=2.14.0",
]

[project.urls]
homepage = "https://github.com/Just-another-Muensterhack/dome-ms-backend"  # TODO
repository = "https://github.com/Just-another-Muensterhack/dome-ms-backend"  # TODO
changelog = "https://github.com/Just-another-Muensterhack/dome-ms-backend/releases"  # TODO
issues = "https://github.com/Just-another-Muensterhack/dome-ms-backend/issues"  # TODO
documentation = "https://github.com/Just-another-Muensterhack/dome-ms-backend/wiki"  # TODO

[dependency-groups]
dev = [
    "jupyterlab>=4.6.3",
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
    "pytest-github-actions-annotate-failures>=0.4.2",
    "pytest-random-order>=1.2.0",
    "pytest-recording>=0.13.4",
    "ruff>=0.16.7",
    "ty>=0.0.81",
]

[tool.uv]
exclude-newer = "P7D"

[tool.ty.environment]
root = ["src/ms_dome"]

[tool.pytest.ini_options]
python_files = ["test_*.py", "*_test.py"]
filterwarnings = ["ignore::DeprecationWarning"]
pythonpath = ["src/ms_dome"]
cache_dir = "/workspaces/.cache/pytest"
addopts = [
    "--cov",
    "--cov-branch",
    "--cov=src",
    "--cov-report=xml",
    "--import-mode=importlib",
]
