# Generated by Django 6.1.1 on 2026-09-25 18:31

import django.db.models.deletion
import uuid
import website.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0003_webserver'),
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteContent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField()),
                ('html', models.FileField(max_length=255, storage=website.models.website_storage, upload_to=website.models.website_html_path)),
                ('model', models.CharField(help_text='The language model that generated the HTML.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='core.website')),
            ],
            options={
                'verbose_name_plural': 'website contents',
            },
        ),
    ]
