# Generated by Django 6.1.1 on 2026-09-25 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text='Categorical data of the website like category, purpose or location.'),
        ),
    ]
