# Generated by Django 6.1.1 on 2026-09-25 21:15

import django.db.models.deletion
from django.db import migrations, models


def activate_existing_contents(apps, schema_editor):
    # before this migration a website had at most one content, it stays the served version
    WebsiteContent = apps.get_model('website', 'WebsiteContent')
    WebsiteContent.objects.update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_webserver'),
        ('website', '0002_content_attributes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websitecontent',
            options={'ordering': ('-created_at',), 'verbose_name_plural': 'website contents'},
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='is_active',
            field=models.BooleanField(default=False, help_text='Whether this version is the one served for the website.'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='prompt',
            field=models.TextField(blank=True, help_text='The change requested from the source version.'),
        ),
        migrations.AddField(
            model_name='websitecontent',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The version this one was edited from, empty for a generated version.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edits', to='website.websitecontent'),
        ),
        migrations.RunPython(activate_existing_contents, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='websitecontent',
            name='website',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='core.website'),
        ),
        migrations.AddConstraint(
            model_name='websitecontent',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('website',), name='website_content_unique_active'),
        ),
    ]
