# Generated by Django 6.1.1 on 2026-09-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_content_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='websitecontent',
            name='kind',
            field=models.CharField(choices=[('generated', 'Generated'), ('uploaded', 'Uploaded')], default='generated', help_text='Whether the version was generated by the language model or uploaded by the user.', max_length=16),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='description',
            field=models.TextField(blank=True, help_text='The description a version was generated from.'),
        ),
        migrations.AlterField(
            model_name='websitecontent',
            name='model',
            field=models.CharField(blank=True, help_text='The language model that generated the HTML, empty for an upload.', max_length=255),
        ),
    ]
