services:
  python:  # TODO change this to your project name
    container_name: python  # TODO change this to your project name
    extra_hosts:
      - host.docker.internal:host-gateway
    init: true
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    env_file:
      - .env
      - path: local.env
        required: false
    volumes:
      - ..:/workspaces:cached
    # Overrides default command so things don't shut down after the process ends.
    command: sleep infinity

  postgres:
    image: postgres:18
    container_name: postgres-dev
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
      - "8000:8000"
    volumes:
      - postgres_data:/var/lib/

volumes:
  postgres_data:
