from uuid import uuid4

from core.models import Website, managed_domain_name
from django.core.files.storage import FileSystemStorage, Storage
from django.db import models


def website_storage() -> Storage:
    """Stores below `MEDIA_ROOT`, every version of a website has its own path so no file is ever replaced."""
    return FileSystemStorage()


def website_content_dir(content: "WebsiteContent") -> str:
    """The directory holding all files of a version, derived from the website and content ids only, never from user
    input."""
    return f"websites/{content.website_id.hex}/{content.id.hex}"  # ty: ignore[unresolved-attribute]


def website_html_path(content: "WebsiteContent", _filename: str) -> str:
    return f"{website_content_dir(content)}/index.html"


class WebsiteContent(models.Model):
    """A version of a website's page, either generated from a description and attributes or uploaded as files. The
    `index.html` of its directory is the entry page. A website has many versions, at most one of them is active."""

    class Kind(models.TextChoices):
        GENERATED = "generated"
        UPLOADED = "uploaded"

    id = models.UUIDField(primary_key=True, default=uuid4, editable=False)
    website = models.ForeignKey(Website, on_delete=models.CASCADE, related_name="contents")
    kind = models.CharField(
        max_length=16,
        choices=Kind,
        default=Kind.GENERATED,
        help_text="Whether the version was generated by the language model or uploaded by the user.",
    )
    name = models.CharField(max_length=255, help_text="Identifies the version to the user, e.g. 'Version 3'.")
    is_active = models.BooleanField(default=False, help_text="Whether this version is the one served for the website.")
    source = models.ForeignKey(
        "self",
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        related_name="edits",
        help_text="The version this one was edited from, empty for a generated version.",
    )
    prompt = models.TextField(blank=True, help_text="The change requested from the source version.")
    description = models.TextField(blank=True, help_text="The description a version was generated from.")
    attributes = models.JSONField(
        default=dict, blank=True, help_text="Categorical data of the website like category, purpose or location."
    )
    html = models.FileField(upload_to=website_html_path, storage=website_storage, max_length=255)
    model = models.CharField(
        max_length=255, blank=True, help_text="The language model that generated the HTML, empty for an upload."
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        verbose_name_plural = "website contents"
        ordering = ("-created_at",)
        constraints = (
            models.UniqueConstraint(
                fields=("website",), condition=models.Q(is_active=True), name="website_content_unique_active"
            ),
        )

    def __str__(self):
        return f"{self.name} of {self.website}"

    @property
    def managed_domain(self) -> str:
        """The subdomain of the base domain this version is served at, whether it is active or not."""
        return managed_domain_name(self.id)  # ty: ignore[invalid-argument-type]

    def read_html(self) -> str:
        with self.html.open("rb") as file:  # ty: ignore[unresolved-attribute]
            return file.read().decode("utf-8")
